"""add admin_role and attribute_privilege_rule models

Revision ID: 0e0cff7ad121
Revises: 929c3845f5a3
Create Date: 2025-11-20 13:48:45.249081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0cff7ad121'
down_revision: Union[str, Sequence[str], None] = '929c3845f5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_admin_role_id'), 'admin_role', ['id'], unique=False)
    op.create_table('attribute_privilege_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.Enum('create', 'read', 'update', 'delete', name='privilegeaction'), nullable=False),
    sa.Column('attribute_key_regex', sa.String(length=1024), nullable=False),
    sa.Column('attribute_value_regex', sa.String(length=1024), nullable=True),
    sa.Column('target_scope', sa.Enum('self', 'any', name='targetscope'), nullable=False),
    sa.Column('required_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['required_role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_privilege_rule_id'), 'attribute_privilege_rule', ['id'], unique=False)
    op.create_table('user_admin_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_admin_role')
    )
    op.create_index(op.f('ix_user_admin_role_id'), 'user_admin_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin_role_id'), table_name='user_admin_role')
    op.drop_table('user_admin_role')
    op.drop_index(op.f('ix_attribute_privilege_rule_id'), table_name='attribute_privilege_rule')
    op.drop_table('attribute_privilege_rule')
    op.drop_index(op.f('ix_admin_role_id'), table_name='admin_role')
    op.drop_table('admin_role')
    # ### end Alembic commands ###
