"""Add unique constraint to privileges

Revision ID: 2619fe99b847
Revises: 9f4c104ad4c3
Create Date: 2026-01-07 10:14:15.381981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2619fe99b847'
down_revision: Union[str, Sequence[str], None] = '9f4c104ad4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_privilege_scope', 'privileges', ['grantee_user_id', 'action', 'attribute_id', 'value_restriction'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_privilege_scope', 'privileges', type_='unique')
    # ### end Alembic commands ###
