"""change colum name from entitlements ro attributes

Revision ID: 566d65326e0f
Revises: 22307527f0e4
Create Date: 2025-08-04 15:37:30.057370

"""
from typing import Sequence, Union
import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '566d65326e0f'
down_revision: Union[str, Sequence[str], None] = '22307527f0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    op.add_column('user', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.String(length=50), nullable=False, server_default=now))
    op.add_column('user', sa.Column('updated_at', sa.String(length=50), nullable=False, server_default=now))
    op.drop_column('user', 'entitlements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('entitlements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'attributes')
    # ### end Alembic commands ###
