"""Add relationships to existing tables

Revision ID: 585f313fa208
Revises: 95f681614b17
Create Date: 2025-07-23 13:33:30.242712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585f313fa208'
down_revision: Union[str, Sequence[str], None] = '95f681614b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_affiliations')
    op.drop_table('users')
    op.drop_table('user_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_groups_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_groups_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('sub', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bw_card_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bw_card_valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bw_card_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preferred_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('given_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('family_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ou', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('upn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('eduperson_principal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_affiliations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('affiliation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_affiliations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_affiliations_pkey'))
    )
    # ### end Alembic commands ###
