"""seperated attributes table from user

Revision ID: 5a7408f06efd
Revises: 
Create Date: 2025-08-07 09:51:58.444483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7408f06efd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=True),
    sa.Column('iss', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub', 'iss', name='uq_user_sub_iss')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_iss'), 'user', ['iss'], unique=False)
    op.create_index(op.f('ix_user_sub'), 'user', ['sub'], unique=False)
    op.create_table('userattribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=1024), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', 'value', name='uq_user_attribute_user_id_key_value')
    )
    op.create_index(op.f('ix_userattribute_id'), 'userattribute', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userattribute_id'), table_name='userattribute')
    op.drop_table('userattribute')
    op.drop_index(op.f('ix_user_sub'), table_name='user')
    op.drop_index(op.f('ix_user_iss'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
