"""Add delete_value to privilege model

Revision ID: 9f4c104ad4c3
Revises: ed79f0afebb2
Create Date: 2025-12-07 20:07:30.408314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4c104ad4c3'
down_revision: Union[str, Sequence[str], None] = 'ed79f0afebb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE privilege_action ADD VALUE 'DELETE_VALUE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
