"""Added new invitsation model

Revision ID: cd48ce93666f
Revises: 
Create Date: 2025-08-23 10:47:43.589053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd48ce93666f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_sub', sa.String(length=1024), nullable=True),
    sa.Column('invited_user_iss', sa.String(length=1024), nullable=True),
    sa.Column('group_key', sa.String(length=1024), nullable=False),
    sa.Column('group_value', sa.String(length=1024), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_hash'), 'invitation', ['hash'], unique=True)
    op.create_index(op.f('ix_invitation_id'), 'invitation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_hash'), table_name='invitation')
    op.drop_table('invitation')
    # ### end Alembic commands ###
