"""delete source from user_attribute_model

Revision ID: ed79f0afebb2
Revises: 3fe8ede5e50c
Create Date: 2025-12-02 10:11:55.735184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed79f0afebb2'
down_revision: Union[str, Sequence[str], None] = '3fe8ede5e50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_attribute_values', 'value',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('user_attribute_values', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attribute_values', sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('user_attribute_values', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
